apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ct7kompjy-python
  janus-idp.io/tekton: ct7kompjy-python
  backstage.io/kubernetes-id: ct7kompjy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ct7kompjy-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
